# Generated by Django 2.2.16 on 2022-11-19 14:27

from django.db import migrations, models
import django.db.models.deletion
import reviews.validate


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genrestitles',
            name='Genres',
        ),
        migrations.AddField(
            model_name='genrestitles',
            name='Genre',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='genre', to='reviews.Genres'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='genrestitles',
            name='Titles',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='titles', to='reviews.Titles'),
        ),
        migrations.AlterField(
            model_name='titles',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categories', to='reviews.Categories'),
        ),
        migrations.AlterField(
            model_name='titles',
            name='year',
            field=models.IntegerField(blank=True, null=True, validators=[reviews.validate.validate_year]),
        ),
    ]
