# Generated by Django 2.2.16 on 2022-11-25 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_user_confirmation_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Админ'), ('moderator', 'Модер'), ('user', 'Подтвержденный пользователь')], default='user', max_length=30, verbose_name='Роль'),
        ),
    ]
