# Generated by Django 2.2.16 on 2022-11-20 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_auto_20221120_1501'),
    ]

    operations = [
        migrations.RenameField(
            model_name='titles',
            old_name='Category',
            new_name='category',
        ),
    ]
